language: node_js
sudo: false
node_js:
- stable
- 7
- 6
env:
  matrix:
  - CMD=test
  - CMD=lint
  - CMD=build:android
  - CMD=build:ios
  - CMD=flow
matrix:
  fast_finish: true
  allow_failures:
  - env: CMD=flow
script:
- yarn $CMD
after_success:
- '[ "$CMD" == "test" ] && yarn coverage'
notifications:
  email: false
